apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: modules
    cyclops-ui.com/write-repo: https://github.com/petar-cvit/gitops-infra
    cyclops-ui.com/write-revision: ""
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cyclops-ui.com/v1alpha1","kind":"Module","metadata":{"annotations":{"cyclops-ui.com/write-path":"modules","cyclops-ui.com/write-repo":"https://github.com/petar-cvit/gitops-infra","cyclops-ui.com/write-revision":""},"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"all-gitops-apps"},"name":"writing","namespace":"cyclops"},"spec":{"targetNamespace":"default","template":{"path":"demo","repo":"https://github.com/cyclops-ui/templates","sourceType":"git","version":"main"},"values":{"image":"nginx","name":"demo-app","replicas":4,"service":true,"version":"1.14.2"}}}
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: all-gitops-apps
  name: writing
spec:
  targetNamespace: default
  template:
    path: demo
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: main
  values:
    image: nginx
    name: demo-app
    replicas: 7
    service: true
    version: 1.14.2
