apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: modules
    cyclops-ui.com/write-repo: https://github.com/petar-cvit/gitops-infra
    cyclops-ui.com/write-revision: ""
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: all-gitops-apps
  name: writing
spec:
  targetNamespace: default
  template:
    path: demo
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: main
  values:
    image: petarcvit223/logs
    name: demo-app
    replicas: 2
    service: true
    version: latest
