apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  name: my-api-db
  namespace: cyclops
spec:
  template:
    path: bitnami/mysql
    repo: https://github.com/bitnami/charts
    version: main
