apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  name: my-api
  namespace: cyclops
spec:
  template:
    path: app-template
    repo: https://github.com/cyclops-ui/templates
    version: main
  values: {}
