apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: cerbic
    app.kubernetes.io/managed-by: cyclops
    app.kubernetes.io/name: cerbos
    app.kubernetes.io/version: 0.46.0
    cyclops.module: cerbic
    helm.sh/chart: cerbos-0.46.0
  name: cerbic-cerbos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cerbic
      app.kubernetes.io/name: cerbos
  template:
    metadata:
      annotations:
        checksum/config: a973ef0eb705dd2d436aeddacd9d1ba9567eba7981f0f14d4e546c6fe4429729
        prometheus.io/path: /_cerbos/metrics
        prometheus.io/port: "3592"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: cerbic
        app.kubernetes.io/name: cerbos
    spec:
      containers:
      - args:
        - server
        - --config=/config/.cerbos.yaml
        - --log-level=INFO
        image: ghcr.io/cerbos/cerbos:0.46.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /_cerbos/health
            port: http
            scheme: HTTP
        name: cerbos
        ports:
        - containerPort: 3592
          name: http
        - containerPort: 3593
          name: grpc
        readinessProbe:
          httpGet:
            path: /_cerbos/health
            port: http
            scheme: HTTP
        resources:
          limits: {}
          requests: {}
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
        - mountPath: /work
          name: work
      serviceAccountName: cerbic-cerbos
      volumes:
      - configMap:
          name: cerbic-cerbos
        name: config
      - emptyDir: {}
        name: work
