apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: cerbic
    app.kubernetes.io/managed-by: cyclops
    app.kubernetes.io/name: cerbos
    app.kubernetes.io/version: 0.46.0
    cyclops.module: cerbic
    helm.sh/chart: cerbos-0.46.0
  name: cerbic-cerbos
spec:
  ports:
  - name: http
    port: 3592
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 3593
    protocol: TCP
    targetPort: grpc
  selector:
    app.kubernetes.io/instance: cerbic
    app.kubernetes.io/name: cerbos
  type: ClusterIP
