apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: cerbic
    app.kubernetes.io/managed-by: cyclops
    app.kubernetes.io/name: cerbos
    app.kubernetes.io/version: 0.46.0
    cyclops.module: cerbic
    helm.sh/chart: cerbos-0.46.0
  name: cerbic-cerbos
