apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: applicationsss
    cyclops-ui.com/write-repo: https://github.com/petar-cvit/gitops-infra
    cyclops-ui.com/write-revision: apps-git-writing-new
  creationTimestamp: null
  name: novi
spec:
  targetNamespace: default
  template:
    path: demo
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: main
  values:
    image: nginx
    name: demo-app
    replicas: 3
    service: true
    version: 1.14.2
