apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: stage
    cyclops-ui.com/write-repo: https://github.com/petar-cvit/gitops-infra
    cyclops-ui.com/write-revision: main
  creationTimestamp: null
  finalizers:
  - cyclops-ui.com/module-resources
  name: deva
spec:
  targetNamespace: default
  template:
    path: demo
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: main
  values:
    image: nginx
    name: demo-app
    replicas: 5
    service: true
    version: 1.14.2
status: {}
