apiVersion: cyclops-ui.com/v1alpha1
kind: Module
metadata:
  annotations:
    cyclops-ui.com/write-path: other-team-apps
    cyclops-ui.com/write-repo: https://github.com/petar-cvit/gitops-infra
    cyclops-ui.com/write-revision: stage-infra
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: my-team-apps
  name: cerbie-module
spec:
  targetNamespace: default
  template:
    path: demo
    repo: https://github.com/cyclops-ui/templates
    sourceType: git
    version: main
  values:
    image: nginx
    name: demo-app
    replicas: 5
    service: true
    version: 1.14.2
status:
  iconURL: https://github.com/cyclops-ui/cyclops/blob/main/cyclops-ui/src/static/img/default-template-icon.png?raw=true
  templateResolvedVersion: ab2756886ba4c9e0e3122e3cbb6dc0338fadc617
